### ISSUE TITLE
How to utilize chunk based file parsing?

### ISSUE THREAD

**Issue by k00ni** [pietercolpaert/hardf#25]
README contains the following code

```php
$writer = new TriGWriter(["format"=>"n-quads"]);
$tripleCallback = function ($error, $triple) use ($writer) {
    if (isset($error))
        throw $error;
    else if (isset($triple)) {
        $writer->write();
        echo $writer->read();
    else if (isset($error)) {
        throw $error;
    } else {
        echo $writer->end();
    }
};
$prefixCallback = function ($prefix, $iri) use (&$writer) {
    $writer->addPrefix($prefix, $iri);
};
$parser = new TriGParser(["format" => "trig"], $tripleCallback, $prefixCallback);
$parser->parseChunk($chunk);
$parser->parseChunk($chunk);
$parser->parseChunk($chunk);
$parser->end(); //Needs to be called
```
But how to get `$chunk`, which is not defined this example? Is it provided by hardf or do i have to get that by myself?

Can you please provide me an example, how to read a RDF file (e.g. n-triples) using chunks? Thanks in advance.

**Comment by pietercolpaert** [comment]
You should get a `$chunk` through a read interface. E.g., something that reads a file line by line, then the `$chunk` would be the line.

**Comment by k00ni** [comment]
Can you handle chunk-based reading when file is in RDF/Turtle format?

**Comment by pietercolpaert** [comment]
Yes, why not?

**Comment by k00ni** [comment]
Because a triple may be "spread out" over multiple lines.

**Comment by pietercolpaert** [comment]
Yes, this is in fact included in a test: https://github.com/pietercolpaert/hardf/blob/master/test/TriGParserTest.php#L844

**Comment by k00ni** [comment]
Thanks for the hint!
